name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:

  # ============================
  # REACT
  # ============================
  frontend_build_job:
    runs-on: ubuntu-latest
    name: Frontend build job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install React dependencies
        run: |
          cd client/react
          npm install

      - name: Build React app
        run: |
          cd client/react
          npm run build

  frontend_deploy_job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy Frontend to Fly.io
    needs: frontend_build_job
    concurrency: frontend-deploy-group

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Frontend
        run: |
          cd client/react
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FRONTEND_TOKEN }}

  # ============================
  # API
  # ============================
  backend_build_test_job:
    runs-on: ubuntu-latest
    name: Backend build & test job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore backend
        run: dotnet restore ./server/api.sln

      - name: Build backend
        run: dotnet build ./server/api.sln --no-restore --configuration Release

      - name: Test backend
        run: dotnet test ./server/api.sln --no-build --configuration Release --verbosity normal

  backend_deploy_job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy Backend to Fly.io
    needs: backend_build_test_job
    concurrency: backend-deploy-group

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend
        run: |
          cd server
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_BACKEND_TOKEN }}